### PR TITLE
create draft case study file for core 2.0

### PR DESCRIPTION
**Pull request by dkp1903**
@aornugent this is a first version - kindly let me know if I am going in the right direction

### CODE REVIEW

**Comment by dkp1903** [comment]
@aornugent completed transferring the entire document to a case study in markdown

**Comment by aornugent** [comment]
Pretty good! Thanks @dkp1903 - could you please also add a Table of Contents? Feel free to add explanatory text or edit the Roadmap for clarity. If you had questions, perhaps you could try the 'Review Changes' feature in Github to leave questions in place and I'll reply ASAP.

**Comment by dkp1903** [comment]
Have added the Table of contents, @aornugent. Please let me know if there's anything else I can add/refactor

**Comment by aornugent** [comment]
@HarshCasper - can you please merge these into the GSoD repo, for later use in the content strategy? The template could be used for your documentation workflow and I'll come back to update the development pipeline in th next month or so.

**Comment by HarshCasper** [comment]
> @HarshCasper - can you please merge these into the GSoD repo, for later use in the content strategy? The template could be used for your documentation workflow and I'll come back to update the development pipeline in th next month or so.

Sure. I will make some edits from my side and I will squash and merge this.

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
