### PR TITLE
Add beginner's guide

### PR DESCRIPTION
**Pull request by sarahhaggarty**
This PR is to import the following [google doc](https://docs.google.com/document/d/1fxAOiL9GX05QN0b5zGafN38cCk7LYP-l0SmvUq1iwB8/edit?pli=1#heading=h.jc136rl5t8oe) into a markdown file as a precursor to a beginner's guide. 

The original file has some good content in it and nice diagrams to explain the FLINT's architecture and general way of processing. However it is definitely an architecture document rather than a beginner's guide currently. It would be good to define and agree the "beginner" that the guide is intended for. Is the ambition to target this document for beginner developers or to expand the scope wider?

I suggest making the introduction more general and providing a couple more sections to ramp up the reader to the more technical content. Some of this content can be ported from other documents. For example, the [Development Guide](https://docs.google.com/document/d/185DrAQ9Tpg0XqwMt26ouzIDRKihJU0MZ2VUYX0L5Bys/edit?pli=1#heading=h.g5ne3borc0an) has a nice appendix introducing FLINT concepts which I think would be good to include here.  Perhaps even bringing the System Design section forward to be after the introduction to FLINT concepts.

A few other suggestions that are included in this PR:

- Writing a "Purpose" for the document. What do we want the reader to get out of reading this document?
- Creating a link for the reader between the core framework components and the key components section.
- Add  a TOC, legends for diagrams, sections for new terms and abbreviations, further reading.
- Converting diagrams into a format where they can be edited by others without a closed tool like LucidChart. I think that this is covered by this [issue](https://github.com/moja-global/Google_Season_of_Documentation/issues/7) already raised.
- Moving System Events until after the System Design section.

@aornugent @HarshCasper , what do you think?

### CODE REVIEW

**Comment by aornugent** [comment]
Thanks @sarahhaggarty! I fully agree with your assessment that the simple FLINT guide isn't quite fit for purpose, but I think your suggestions to make it more general are heading in the right direction. Well done for finding examples of the content that you'd like to see.

In terms of intended audience, I think it would be useful to consider both a user and a developer. It's helpful for both to understand the general FLINT concepts, as well as the process that occurs during a FLINT run, but a beginner developer would probably be more interested in 'how it works' and a user would like to know 'what it does'.

@HarshCasper might have some suggestions about how to manage this, but perhaps we can merge this PR as a starting point and open a new issue that describes the general problem of how we organise this kind of content. Would a high-level design document be a useful way to discuss potential solutions?

**Comment by aornugent** [comment]
Here is another source of potentially useful diagrams and outlines, at varying levels of detail and complexity:
https://docs.google.com/presentation/d/1xDi39D7Xkexn5GBxpvqx6-Wit4YYi3YfGPBaTFNEyoU/edit?usp=sharing

**Comment by sarahhaggarty** [comment]
Thanks for your feedback @aornugent! Yes, I also think it would be good to cover both users and developers as it would help make FLINT more accessible. I think that we can create a beginner's guide that encompasses both audiences as even in your example I would expect that a beginner developer is first curious to know what FLINT does and then want to know about how it works to achieve this.

At the moment the PR contains two commits: 1. for a 1:1 transcription of the original google doc into markdown and 2. a suggested skeleton to enhance the beginner's guide further. I'd suggest that if you want to merge the PR that we only merge the first commit. I can revert the second commit and create a new issue to continue discussion on this. Would this issue be just for the beginner's guide or were you actually meaning a broader topic about how to manage documentation in general for users versus developers? If it's just for this guide I can link a google doc to the new issue with a draft framework for the guide to allow others to review and provide their feedback.

Thanks for sharing the presentation. I'm intrigued by the different output examples presented there. Is there a definitive list somewhere already of all the inputs and outputs of the FLINT and their file formats?

**Comment by sarahhaggarty** [comment]
@all-contributors please add @sarahhaggarty  for doc

**Comment by aornugent** [comment]
> I'd suggest that if you want to merge the PR that we only merge the first commit. I can revert the second commit and create a new issue to continue discussion on this.

This sounds good - maybe you can cross post in #documentation to get additional input on what topics make a good user guide.

> Would this issue be just for the beginner's guide or were you actually meaning a broader topic about how to manage documentation in general for users versus developers? 

We loosely have a plan but need to publish it more clearly. Roughly - the community website will be to failicate onboarding in the community, hosting introductory materials, promoting developments and updates on moja global projects and a Working Group notice board. More technical documentation for specific projects, like FLINT and the IPCC Reporting tool, have additional pages at docs.moja.global.

I'd like to see the community website publish 'case studies' that might be of interest to both users and developers, scientists, policy makers and and any other kind of contributor in between.

**Pull request merged**
